;; renamed lambdas/lets: 1
 
(define fix (<change>
      (let ((z (lambda (P)
                 (lambda (u)
                    (lambda (t)
                       (lambda (t)
                          (lambda (i)
                             (lambda (n)
                                (lambda (g)
                                   (lambda (S)
                                      (lambda (c)
                                         (lambda (h)
                                            (lambda (e)
                                               (lambda (m)
                                                  (lambda (e)
                                                     (lambda (t)
                                                        (lambda (o)
                                                           (lambda (W)
                                                              (lambda (o)
                                                                 (lambda (r)
                                                                    (lambda (k)
                                                                       (lambda (!)
                                                                          (!
                                                                             (lambda (break)
                                                                                (((((((((((((((((((((W o) r) k) W) o) r) k) W) o) r) k) W) o) r) k) W) o) r) k) !) break)))))))))))))))))))))))))
         (let ((Z z))
            (((((((((((((((((((z z) z) z) z) z) Z) Z) Z) Z) Z) Z) Z) z) z) z) z) z) z) z)))
      (let ((_z0 (lambda (_P0)
                   (lambda (_u0)
                      (lambda (_t0)
                         (lambda (_t1)
                            (lambda (_i0)
                               (lambda (_n0)
                                  (lambda (_g0)
                                     (lambda (_S0)
                                        (lambda (_c0)
                                           (lambda (_h0)
                                              (lambda (_e0)
                                                 (lambda (_m0)
                                                    (lambda (_e1)
                                                       (lambda (_t2)
                                                          (lambda (_o0)
                                                             (lambda (_W0)
                                                                (lambda (_o1)
                                                                   (lambda (_r0)
                                                                      (lambda (_k0)
                                                                         (lambda (_!0)
                                                                            (_!0
                                                                               (lambda (_break0)
                                                                                  (((((((((((((((((((((_W0 _o1) _r0) _k0) _W0) _o1) _r0) _k0) _W0) _o1) _r0) _k0) _W0) _o1) _r0) _k0) _W0) _o1) _r0) _k0) _!0)
                                                                                     _break0)))))))))))))))))))))))))
         (let ((_Z0 _z0))
            (((((((((((((((((((_z0 _z0) _z0) _z0) _z0) _z0) _Z0) _Z0) _Z0) _Z0) _Z0) _Z0) _Z0) _z0) _z0) _z0) _z0) _z0) _z0)
               _z0)))))
 
((fix (lambda (f) (lambda (n) (if (zero? n) 1 (* n (f (- n 1))))))) 9)
 
