name: MAF tests on action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run fast tests
    runs-on: ubuntu-latest
    steps:
      # Send a notification to Slack.
      - name: Notify push
        id: slack
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: maf-logs
          status: STARTED
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      # Check out the GitHub repository.
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15
      - name: Setup Z3 
        uses: pavpanchekha/setup-z3@0.2.0
        with: 
          version: 4.8.12
          distribution: glibc-2.31
      # Compile the code.
      - name: Compile MAF
        run: sbt compile
      # Perform the actual tests.
      - name: Run the tests
        run: sbt "maf/testOnly -- -l SlowTest"
      # If successful, update the Slack notification.
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: maf-logs
          status: SUCCESS
          color: good
      # If failed, update the Slack notification.
      - name: Notify slack fail
        if: failure() || cancelled()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: maf-logs
          status: FAILED
          color: danger
      # Send an additional notification upon failure.
      #- name: Stress slack fail
      #  if: failure()
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}
      #  uses: 8398a7/action-slack@v3
      #  with:
      #    status: ${{ job.status }}
      #    fields: message,commit,author
